{{- $dockerconfigjson := include "kova.registryConfigJsonB64" . -}}
{{- $image := include "kova.roleImage" (dict "root" . "role" "worker") -}}
{{- $imagePullSecretName := include "kova.imagePullSecretName" . -}}
{{- if and (eq (include "kova.imagePullSecretsEnabled" .) "true") $imagePullSecretName (.Values.imagePullSecrets.create | default false) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $imagePullSecretName }}
  namespace: {{ include "kova.namespace" . }}
  labels:
    {{- include "kova.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfigjson | quote }}
{{- end }}

---

{{- if and (eq (include "kova.imagePullSecretsEnabled" .) "true") $imagePullSecretName (.Values.imagePullSecrets.create | default false) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $imagePullSecretName }}
  namespace: default
  labels:
    {{- include "kova.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfigjson | quote }}
  kova-image: {{ $image | b64enc | quote }}
{{- end }}
