{{- $dockerconfigjson := include "kova.registryConfigJsonB64" . -}}
{{- $imagePullSecretName := include "kova.imagePullSecretName" . -}}
{{- $createSecret := and (eq (include "kova.imagePullSecretsEnabled" .) "true") $imagePullSecretName (.Values.imagePullSecrets.create | default false) -}}
{{- $releaseNamespace := include "kova.namespace" . -}}
{{- if $createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $imagePullSecretName }}
  namespace: {{ $releaseNamespace }}
  labels:
    {{- include "kova.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfigjson | quote }}
{{- end }}
{{- $runnerNamespace := default $releaseNamespace .Values.serviceDaemon.runnerNamespace -}}
{{- $runnerSecretName := default $imagePullSecretName .Values.serviceDaemon.runnerImagePullSecret -}}
{{- if and $createSecret .Values.serviceDaemon.enabled (ne $runnerNamespace $releaseNamespace) (eq $runnerSecretName $imagePullSecretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $imagePullSecretName }}
  namespace: {{ $runnerNamespace }}
  labels:
    {{- include "kova.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfigjson | quote }}
{{- end }}
