apiVersion: v1
kind: Service
metadata:
  name: {{ include "kova.fullname" . }}
  namespace: {{ include "kova.namespace" . }}
  labels:
    {{- include "kova.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  clusterIPs:
    {{- toYaml .Values.service.clusterIPs | nindent 4 }}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }}
  ipFamilies:
    {{- toYaml .Values.service.ipFamilies | nindent 4 }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  ports:
    - name: {{ .Values.container.portName }}
      port: {{ .Values.service.port }}
      protocol: {{ .Values.container.protocol }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "kova.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  type: {{ .Values.service.type }}
