{{- if and .Values.serviceDaemon.enabled (eq .Values.artifactStore.driver "filesystem") .Values.artifactStore.filesystem.pvc.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kova.sourcePVCName" . }}
  namespace: {{ include "kova.namespace" . }}
  labels:
    {{- include "kova.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.artifactStore.filesystem.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.artifactStore.filesystem.pvc.size }}
  {{- with .Values.artifactStore.filesystem.pvc.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
