kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5003"]
      endpoint = ["http://kind-registry-crd-upgrade:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-registry-crd-upgrade:5000"]
      endpoint = ["http://kind-registry-crd-upgrade:5000"]
nodes:
  - role: control-plane
  - role: worker
