//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildResult) DeepCopyInto(out *BuildResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildResult.
func (in *BuildResult) DeepCopy() *BuildResult {
	if in == nil {
		return nil
	}
	out := new(BuildResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildResultSummary) DeepCopyInto(out *BuildResultSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildResultSummary.
func (in *BuildResultSummary) DeepCopy() *BuildResultSummary {
	if in == nil {
		return nil
	}
	out := new(BuildResultSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KovaBuild) DeepCopyInto(out *KovaBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KovaBuild.
func (in *KovaBuild) DeepCopy() *KovaBuild {
	if in == nil {
		return nil
	}
	out := new(KovaBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KovaBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KovaBuildList) DeepCopyInto(out *KovaBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KovaBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KovaBuildList.
func (in *KovaBuildList) DeepCopy() *KovaBuildList {
	if in == nil {
		return nil
	}
	out := new(KovaBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KovaBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KovaBuildOptions) DeepCopyInto(out *KovaBuildOptions) {
	*out = *in
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KovaBuildOptions.
func (in *KovaBuildOptions) DeepCopy() *KovaBuildOptions {
	if in == nil {
		return nil
	}
	out := new(KovaBuildOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KovaBuildRequester) DeepCopyInto(out *KovaBuildRequester) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KovaBuildRequester.
func (in *KovaBuildRequester) DeepCopy() *KovaBuildRequester {
	if in == nil {
		return nil
	}
	out := new(KovaBuildRequester)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KovaBuildSourceSpec) DeepCopyInto(out *KovaBuildSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KovaBuildSourceSpec.
func (in *KovaBuildSourceSpec) DeepCopy() *KovaBuildSourceSpec {
	if in == nil {
		return nil
	}
	out := new(KovaBuildSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KovaBuildSpec) DeepCopyInto(out *KovaBuildSpec) {
	*out = *in
	out.Requester = in.Requester
	out.Source = in.Source
	in.Build.DeepCopyInto(&out.Build)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KovaBuildSpec.
func (in *KovaBuildSpec) DeepCopy() *KovaBuildSpec {
	if in == nil {
		return nil
	}
	out := new(KovaBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KovaBuildStatus) DeepCopyInto(out *KovaBuildStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	out.ResultSummary = in.ResultSummary
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]BuildResult, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KovaBuildStatus.
func (in *KovaBuildStatus) DeepCopy() *KovaBuildStatus {
	if in == nil {
		return nil
	}
	out := new(KovaBuildStatus)
	in.DeepCopyInto(out)
	return out
}
